[package]
name = "idea"
version = "0.0.0"
edition = "2021"

[dependencies]
bitflags = "2.4.1"
eframe = "0.25.0"
egui = "0.25.0"
egui-phosphor = "0.3.2"
egui_extras = "0.25.0"
log = "0.4.20"
once_cell = "1.19.0"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
env_logger = "0.10.0"

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen-futures = "0.4.39"

[profile.release]
# TODO: experiment with this later on
# normally it's set to 3 but 2 results in a smaller binary (at least in wasm)
# see which is faster
# opt-level = 2