name: Build web

on:
  push:

jobs:
  build-web:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Install Trunk
        run: cargo binstall trunk
    
      - name: Install wasm32
        run: rustup target add wasm32-unknown-unknown

      - name: Build for web
        run: trunk build --release --features epic

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: "nitrous-web"
          path: "dist"
